# Generated by Django 2.0.5 on 2019-09-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
